language: php

php:
  - 5.3
  - 5.4
  
before_script:
  - composer self-update && composer --version
  - composer require satooshi/php-coveralls 0.6.*
  - composer update --prefer-source
  
script: 
  - phpunit --coverage-clover tests/unit/runtime/coveralls/clover.xml

after_script:
  - php vendor/bin/coveralls
